"""empty message

Revision ID: bd84ceafbe27
Revises: 
Create Date: 2018-10-31 09:10:43.271266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd84ceafbe27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nb_season', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('url_picture_tvshow', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('realisateur', sa.String(length=50), nullable=True),
    sa.Column('name_act', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_serie')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_notification_read_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('saison',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_saison', sa.Integer(), nullable=True),
    sa.Column('nb_episode', sa.Integer(), nullable=True),
    sa.Column('url_picture_season', sa.String(), nullable=True),
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watching',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_serie')
    )
    op.create_table('episode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_ep', sa.Integer(), nullable=True),
    sa.Column('ep_name', sa.String(length=50), nullable=True),
    sa.Column('ep_sum', sa.Text(), nullable=True),
    sa.Column('ep_date', sa.DateTime(), nullable=True),
    sa.Column('id_saison', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_saison'], ['saison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_episode', sa.Integer(), nullable=True),
    sa.Column('id_recipient', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_episode'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['id_recipient'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('episode')
    op.drop_table('watching')
    op.drop_table('saison')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('serie')
    # ### end Alembic commands ###
